pwdft: k_point Module Reference
k_point Module Reference
Functions/Subroutines
subroutine ksum_rho ()
subroutine ksum_dos ()
DOS.
Variables
integer, save nk
integer, dimension(3), save kgrd
integer, dimension(:,:), allocatable, save tetra
real(8), dimension(:,:), allocatable, save kvec
Function/Subroutine Documentation
ksum_rho()
subroutine k_point::ksum_rho
Definition at line 35 of file k_point.F90.
     !
     use atm_spec, only : bvec, nelec
     use kohn_sham, only : nbnd, ef, eval, evec
     use fftw_wrapper, only : fft_g2r_w
     use rho_v, only : rho
     use gvec, only : g_rh, g_wf
     use libtetrabz, only : libtetrabz_fermieng
     !
     integer :: ik, ibnd
     real(8) :: occ(nbnd,nk)
     complex(8) :: psir(g_rh%nr)
     !
     call libtetrabz_fermieng(2,bvec,nbnd,kgrd,eval,kgrd,occ,ef,nelec*0.5d0)
     !
     rho(1:g_rh%nr) = 0.0d0
     do ik = 1, nk
        do ibnd = 1, nbnd
           call fft_g2r_w(evec(1:g_wf%npw,ibnd,ik), psir)
           rho(1:g_rh%nr) = rho(1:g_rh%nr) &
           &              + dble(conjg(psir(1:g_rh%nr))*psir(1:g_rh%nr))*occ(ibnd,ik)*2.0d0
        end do
     end do
     !
References atm_spec::bvec, kohn_sham::ef, kohn_sham::eval, kohn_sham::evec, fftw_wrapper::fft_g2r_w(), gvec::g_rh, gvec::g_wf, kgrd, kohn_sham::nbnd, atm_spec::nelec, and rho_v::rho.
Referenced by scf::kohn_sham_eq().
ksum_dos()
subroutine k_point::ksum_dos
DOS.
Definition at line 63 of file k_point.F90.
     !
     use constant, only : htr2ev
     use atm_spec, only : bvec
     use kohn_sham, only : nbnd, ef, eval
     use libtetrabz, only : libtetrabz_dos, libtetrabz_intdos
     !
     integer,parameter :: ne = 500
     integer :: ie, fo = 20
     real(8) :: e0(ne), dos(ne), intdos(ne), wght(ne,nbnd,nk), &
     &          emax, emin, de
     !
     emax = maxval(eval(1:nbnd,1:nk))
     emin = minval(eval(1:nbnd,1:nk))
     de = (emax - emin) / dble(ne)
     do ie = 1, ne
        e0(ie) = emin + de * (ie -1)
     end do
     !
     call libtetrabz_dos(2,bvec,nbnd,kgrd,eval,kgrd,wght,ne,e0)
     !
     do ie = 1, ne
        dos(ie) = sum(wght(ie,1:nbnd,1:nk))
     end do
     !
     call libtetrabz_intdos(2,bvec,nbnd,kgrd,eval,kgrd,wght,ne,e0)
     !
     do ie = 1, ne
        intdos(ie) = sum(wght(ie,1:nbnd,1:nk))
     end do
     !
     write(*,*) "  Output dos.dat"
     open(fo, file = "dos.dat")
     !
     write(fo,*) "# Energy[eV]  DOS[eV^-1]  IntDOS"
     !
     do ie = 1, ne
        write(fo,*) (e0(ie)-ef)*htr2ev, dos(ie)*2.0d0/htr2ev, intdos(ie)*2.0d0
     end do
     !
     close(fo)
     !
References atm_spec::bvec, kohn_sham::ef, kohn_sham::eval, constant::htr2ev, kgrd, and kohn_sham::nbnd.
Referenced by pwdft().
Variable Documentation
nk
integer, save k_point::nk
Definition at line 27 of file k_point.F90.
   integer,save :: nk
Referenced by plot::band_plot(), plot::fermi_plot(), energy::kinetic(), scf::kohn_sham_eq(), pwdft(), and stdin::read_stdin().
kgrd
integer, dimension(3), save k_point::kgrd
Definition at line 28 of file k_point.F90.
   integer,save :: kgrd(3)
Referenced by plot::fermi_plot(), energy::kinetic(), ksum_dos(), ksum_rho(), and stdin::read_stdin().
tetra
integer, dimension(:,:), allocatable, save k_point::tetra
Definition at line 29 of file k_point.F90.
   integer,allocatable,save :: tetra(:,:)
kvec
real(8), dimension(:,:), allocatable, save k_point::kvec
Definition at line 30 of file k_point.F90.
   real(8),allocatable,save :: kvec(:,:)
Referenced by plot::band_plot(), plot::fermi_plot(), energy::kinetic(), scf::kohn_sham_eq(), and stdin::read_stdin().