pwdft: libtetrabz_occ_mod Module Reference
libtetrabz_occ_mod Module Reference
Functions/Subroutines
subroutine, public libtetrabz_occ (ltetra, bvec, nb, nge, eig, ngw, wght, comm)
subroutine, public libtetrabz_fermieng (ltetra, bvec, nb, nge, eig, ngw, wght, ef, nelec, comm)
subroutine libtetrabz_occ_main (wlsm, nt_local, ik_global, ik_local, nb, nkBZ, eig, nk_local, occ, ef)
Function/Subroutine Documentation
libtetrabz_occ()
subroutine, public libtetrabz_occ_mod::libtetrabz_occ (integer(c_int), intent(in) ltetra, real(c_double), dimension(9), intent(in) bvec, integer(c_int), intent(in) nb, integer(c_int), dimension(3), intent(in) nge, real(c_double), dimension(nb,product(nge(1:3))), intent(in) eig, integer(c_int), dimension(3), intent(in) ngw, real(c_double), dimension(nb,product(ngw(1:3))), intent(out) wght, integer(c_int), intent(in), optional comm)
Definition at line 35 of file libtetrabz_occ_mod.F90.
   !
   USE iso_c_binding
   USE libtetrabz_common, ONLY : libtetrabz_initialize, libtetrabz_interpol_indx, libtetrabz_mpisum_dv
   IMPLICIT NONE
   !
   INTEGER(C_INT),INTENT(IN) :: ltetra, nb, nge(3), ngw(3)
   REAL(C_DOUBLE),INTENT(IN) :: bvec(9), eig(nb,PRODUCT(nge(1:3)))
   REAL(C_DOUBLE),INTENT(OUT) :: wght(nb,PRODUCT(ngw(1:3)))
   INTEGER(C_INT),INTENT(IN),OPTIONAL :: comm
   !
   LOGICAL :: linterpol
   INTEGER :: nt_local, nk_local, nkBZ, ik, kintp(8)
   INTEGER,ALLOCATABLE :: ik_global(:,:), ik_local(:,:)
   REAL(8) :: wlsm(4,20), wintp(1,8)
   REAL(8),ALLOCATABLE :: wghtd(:,:,:), kvec(:,:)
   !
   IF(PRESENT(comm)) THEN
      CALL libtetrabz_initialize(ltetra,nge,ngw,bvec,linterpol,wlsm,nk_local,&
      &                          nt_local,nkbz,ik_global,ik_local,kvec,comm)
   ELSE
      CALL libtetrabz_initialize(ltetra,nge,ngw,bvec,linterpol,wlsm,nk_local,&
      &                          nt_local,nkbz,ik_global,ik_local,kvec)
   END IF
   !
   IF(linterpol) THEN
      !
      ALLOCATE(wghtd(nb,1,nk_local))
      CALL libtetrabz_occ_main(wlsm,nt_local,ik_global,ik_local,nb,nkbz,eig,nk_local,wghtd,0d0)
      !
      ! Interpolation
      !
      wght(1:nb,1:product(ngw(1:3))) = 0d0
      DO ik = 1, nk_local
         CALL libtetrabz_interpol_indx(ngw,kvec(1:3,ik),kintp,wintp)
         wght(1:nb,kintp(1:8)) = wght(1:nb,             kintp(1:8)) &
         &                 + matmul(wghtd(1:nb,1:1,ik), wintp(1:1,1:8))
      END DO ! ik = 1, nk_local
      DEALLOCATE(wghtd, kvec)
      !
      IF(PRESENT(comm)) CALL libtetrabz_mpisum_dv(comm, nb * product(ngw(1:3)), wght)
      !
   ELSE
      CALL libtetrabz_occ_main(wlsm,nt_local,ik_global,ik_local,nb,nkbz,eig,nk_local,wght,0d0)
   END IF
   !
   DEALLOCATE(ik_global, ik_local)
   !
References libtetrabz_common::libtetrabz_initialize(), libtetrabz_common::libtetrabz_interpol_indx(), libtetrabz_common::libtetrabz_mpisum_dv(), and libtetrabz_occ_main().
libtetrabz_fermieng()
subroutine, public libtetrabz_occ_mod::libtetrabz_fermieng (integer(c_int), intent(in) ltetra, real(c_double), dimension(9), intent(in) bvec, integer(c_int), intent(in) nb, integer(c_int), dimension(3), intent(in) nge, real(c_double), dimension(nb,product(nge(1:3))), intent(in) eig, integer(c_int), dimension(3), intent(in) ngw, real(c_double), dimension(nb,product(ngw(1:3))), intent(out) wght, real(c_double), intent(out) ef, real(c_double), intent(in) nelec, integer(c_int), intent(in), optional comm)
Definition at line 87 of file libtetrabz_occ_mod.F90.
   !
   USE iso_c_binding
   USE libtetrabz_common, ONLY : libtetrabz_initialize, libtetrabz_interpol_indx, &
   &                             libtetrabz_mpisum_d, libtetrabz_mpisum_dv
   IMPLICIT NONE
   !
   INTEGER(C_INT),INTENT(IN) :: ltetra, nb, nge(3), ngw(3)
   REAL(C_DOUBLE),INTENT(IN) :: bvec(9), nelec, eig(nb,PRODUCT(nge(1:3)))
   REAL(C_DOUBLE),INTENT(OUT) :: ef
   REAL(C_DOUBLE),INTENT(OUT) :: wght(nb,PRODUCT(ngw(1:3)))
   INTEGER(C_INT),INTENT(IN),OPTIONAL :: comm
   !
   LOGICAL :: linterpol
   INTEGER :: nt_local, nk_local, nkBZ, ik, kintp(8)
   INTEGER,ALLOCATABLE :: ik_global(:,:), ik_local(:,:)
   REAL(8) :: wlsm(4,20), wintp(1,8)
   REAL(8),ALLOCATABLE :: wghtd(:,:,:), kvec(:,:)
   !
   INTEGER :: iter, maxiter = 300
   REAL(8) :: elw, eup, eps= 1d-10, sumkmid
   !
   IF(PRESENT(comm)) THEN
      CALL libtetrabz_initialize(ltetra,nge,ngw,bvec,linterpol,wlsm,nk_local,&
      &                          nt_local,nkbz,ik_global,ik_local,kvec,comm)
   ELSE
      CALL libtetrabz_initialize(ltetra,nge,ngw,bvec,linterpol,wlsm,nk_local,&
      &                          nt_local,nkbz,ik_global,ik_local,kvec)
   END IF
   !
   IF(linterpol) ALLOCATE(wghtd(nb,1,nk_local))
   !
   elw = minval(eig(1:nb,1:product(nge(1:3))))
   eup = maxval(eig(1:nb,1:product(nge(1:3))))
   !
   ! Bisection method
   !
   DO iter = 1, maxiter
      !
      ef = (eup + elw) / 2.d0
      !
      ! Calc. # of electrons
      !
      IF(linterpol) THEN
         CALL libtetrabz_occ_main(wlsm,nt_local,ik_global,ik_local,nb,nkbz,eig,nk_local,wghtd,ef)
         sumkmid = sum(wghtd(1:nb,1,1:nk_local))
         !
         IF(PRESENT(comm)) CALL libtetrabz_mpisum_d(comm,sumkmid)
         !
      ELSE
         CALL libtetrabz_occ_main(wlsm,nt_local,ik_global,ik_local,nb,nkbz,eig,nk_local,wght,ef)
         sumkmid = sum(wght(1:nb,1:nk_local))
      END IF
      !
      ! convergence check
      !
      IF(abs(sumkmid - nelec) < eps) THEN
         EXIT
      ELSE IF(sumkmid < nelec) THEN
         elw = ef
      ELSE
         eup = ef
      ENDIF
      !
   END DO  ! iter
   !
   IF(iter >= maxiter) stop "libtetrabz_fermieng"
   !
   IF(linterpol) THEN
      !
      ! Interpolation
      !
      wght(1:nb,1:product(ngw(1:3))) = 0d0
      DO ik = 1, nk_local
         CALL libtetrabz_interpol_indx(ngw,kvec(1:3,ik),kintp,wintp)
         wght(1:nb,kintp(1:8)) = wght(1:nb,             kintp(1:8)) &
         &             + matmul(wghtd(1:nb,1:1,ik), wintp(1:1,1:8))
      END DO ! ik = 1, nk_local
      DEALLOCATE(wghtd, kvec)
      !
      IF(PRESENT(comm)) CALL libtetrabz_mpisum_dv(comm, nb * product(ngw(1:3)), wght)
      !
   END IF ! (linterpol)
   !
   DEALLOCATE(ik_global, ik_local)
   !
References libtetrabz_common::libtetrabz_initialize(), libtetrabz_common::libtetrabz_interpol_indx(), libtetrabz_common::libtetrabz_mpisum_d(), libtetrabz_common::libtetrabz_mpisum_dv(), and libtetrabz_occ_main().
libtetrabz_occ_main()
subroutine libtetrabz_occ_mod::libtetrabz_occ_main (real(8), dimension(4,20), intent(in) wlsm, integer, intent(in) nt_local, integer, dimension(20,nt_local), intent(in) ik_global, integer, dimension(20,nt_local), intent(in) ik_local, integer, intent(in) nb, integer, intent(in) nkBZ, real(8), dimension(nb,nkbz), intent(in) eig, integer, intent(in) nk_local, real(8), dimension(nb,nk_local), intent(out) occ, real(8), intent(in) ef)
Definition at line 177 of file libtetrabz_occ_mod.F90.
   !
   USE libtetrabz_common, ONLY : libtetrabz_sort, &
   &                             libtetrabz_tsmall_a1, libtetrabz_tsmall_b1, &
   &                             libtetrabz_tsmall_b2, libtetrabz_tsmall_b3, &
   &                             libtetrabz_tsmall_c1, libtetrabz_tsmall_c2, &
   &                             libtetrabz_tsmall_c3
   IMPLICIT NONE
   !
   INTEGER,INTENT(IN) :: nt_local, nb, nkBZ, nk_local, &
   &                     ik_global(20,nt_local), ik_local(20,nt_local)
   REAL(8),INTENT(IN) :: wlsm(4,20), ef, eig(nb,nkBZ)
   REAL(8),INTENT(OUT) :: occ(nb,nk_local)
   !
   INTEGER :: ib, indx(4), it
   REAL(8) :: e(4), ei1(4,nb), tsmall(4,4), V, w1(4)
   !
   occ(1:nb,1:nk_local) = 0d0
   !
   !$OMP PARALLEL DEFAULT(NONE) &
   !$OMP & SHARED(ef,eig,ik_global,ik_local,nb,nt_local,occ,wlsm) &
   !$OMP & PRIVATE(e,ei1,ib,indx,it,tsmall,V,w1)
   !
   DO it = 1, nt_local
      !
      DO ib = 1, nb
         ei1(1:4,ib) = matmul(wlsm(1:4,1:20), eig(ib,ik_global(1:20,it)))
      END DO
      !
      !$OMP DO
      DO ib = 1, nb
         !
         w1(1:4) = 0d0
         e(1:4) = ei1(1:4, ib) - ef
         CALL libtetrabz_sort(4,e,indx)
         !
         IF(e(1) <= 0d0 .AND. 0d0 < e(2)) THEN
            !
            CALL libtetrabz_tsmall_a1(e,v,tsmall)
            w1(indx(1:4)) = w1(indx(1:4)) + v * sum(tsmall(1:4,1:4), 1) * 0.25d0
            !
         ELSE IF(e(2) <= 0d0 .AND. 0d0 < e(3)) THEN
            !
            CALL libtetrabz_tsmall_b1(e,v,tsmall)
            w1(indx(1:4)) = w1(indx(1:4)) + v * sum(tsmall(1:4,1:4), 1) * 0.25d0
            !
            CALL libtetrabz_tsmall_b2(e,v,tsmall)
            w1(indx(1:4)) = w1(indx(1:4)) + v * sum(tsmall(1:4,1:4), 1) * 0.25d0
            !
            CALL libtetrabz_tsmall_b3(e,v,tsmall)
            w1(indx(1:4)) = w1(indx(1:4)) + v * sum(tsmall(1:4,1:4), 1) * 0.25d0
            !
         ELSE IF(e(3) <= 0d0 .AND. 0d0 < e(4)) THEN
            !
            CALL libtetrabz_tsmall_c1(e,v,tsmall)
            w1(indx(1:4)) = w1(indx(1:4)) + v * sum(tsmall(1:4,1:4), 1) * 0.25d0
            !
            CALL libtetrabz_tsmall_c2(e,v,tsmall)
            w1(indx(1:4)) = w1(indx(1:4)) + v * sum(tsmall(1:4,1:4), 1) * 0.25d0
            !
            CALL libtetrabz_tsmall_c3(e,v,tsmall)
            w1(indx(1:4)) = w1(indx(1:4)) + v * sum(tsmall(1:4,1:4), 1) * 0.25d0
            !
         ELSE IF(e(4) <= 0d0) THEN
            !
            w1(1:4) = 0.25d0
            !
         ELSE
            !
            cycle
            !
         END IF
         !
         occ(ib,ik_local(1:20,it)) = occ(ib,ik_local(1:20,it)) &
         &                + matmul(w1(1:4), wlsm(1:4,1:20))
         !
      END DO ! ib
      !$OMP END DO NOWAIT
      !
   END DO ! it
   !
   !$OMP END PARALLEL
   !
   occ(1:nb,1:nk_local) = occ(1:nb,1:nk_local) / dble(6 * nkbz)
   !
References libtetrabz_common::libtetrabz_sort(), libtetrabz_common::libtetrabz_tsmall_a1(), libtetrabz_common::libtetrabz_tsmall_b1(), libtetrabz_common::libtetrabz_tsmall_b2(), libtetrabz_common::libtetrabz_tsmall_b3(), libtetrabz_common::libtetrabz_tsmall_c1(), libtetrabz_common::libtetrabz_tsmall_c2(), and libtetrabz_common::libtetrabz_tsmall_c3().
Referenced by libtetrabz_fermieng(), and libtetrabz_occ().