pwdft: gvec Module Reference
gvec Module Reference
Data Types
type fft
Functions/Subroutines
subroutine setup_gvec (xfft, g2cut)
subroutine base2357 (nfft)
Variables
type(fft), save g_rh
type(fft), save g_wf
Function/Subroutine Documentation
setup_gvec()
subroutine gvec::setup_gvec (type(fft), intent(out) xfft, real(8), intent(in) g2cut)
Definition at line 43 of file gvec.F90.
     !
     use constant, only : pi
     use atm_spec, only : avec, bvec
     !
     real(8),intent(in) :: g2cut
     type(fft),intent(out) :: xfft
     !
     integer :: ii, i1, i2, i3, nmax3(3), nmax
     real(8) :: norm, gv0(3), g2
     integer,allocatable :: mill0(:,:)
     !
     do ii = 1, 3
        norm = sqrt(dot_product(avec(1:3,ii), avec(1:3,ii)))
        nmax3(ii) = ceiling(sqrt(g2cut)*norm/(2.0d0*pi))
     end do
     !
     nmax = product(nmax3(1:3)*2+1)
     allocate(mill0(3,nmax))
     !
     xfft%npw = 0
     do i3 = -nmax3(3), nmax3(3)
        do i2 = -nmax3(2), nmax3(2)
           do i1 = -nmax3(1), nmax3(1)
              gv0(1:3) = matmul(bvec(1:3,1:3), dble((/i1,i2,i3/)))
              g2 = dot_product(gv0,gv0)
              if(g2 < g2cut) then
                 xfft%npw = xfft%npw + 1
                 mill0(1:3,xfft%npw) = (/i1,i2,i3/)
              end if
           end do
        end do
     end do
     !
     write(*,*) "    Numver of PW inside sphere : ", xfft%npw
     !
     ! Find FFT grid
     !
     do ii = 1, 3
        xfft%nft(ii) = maxval(mill0(ii,1:xfft%npw))*2 + 1
        call base2357(xfft%nft(ii))
     end do
     !
     write(*,*) "    FFT grid : ", xfft%nft(1:3)
     xfft%nr = product(xfft%nft(1:3))
     write(*,*) "    Numver of PW in grid : ", xfft%nr
     allocate(xfft%mill(3,xfft%nr), xfft%map(xfft%npw))
     !
     ! Whole grid : Miller index
     !
     ii = 0
     do i3 = 0, xfft%nft(3) - 1
        do i2 = 0, xfft%nft(2) - 1
           do i1 = 0, xfft%nft(1) - 1
              ii = ii + 1
              xfft%mill(1:3,ii) = modulo((/i1, i2, i3/) + xfft%nft(1:3)/2, xfft%nft(1:3)) &
              &                                         - xfft%nft(1:3)/2
           end do
        end do
     end do
     !
     ! Mapper
     !
     do ii = 1, xfft%npw
        mill0(1:3,ii) = modulo(mill0(1:3,ii), xfft%nft(1:3))
        xfft%map(ii) = 1 + mill0(1,ii) + xfft%nft(1)*(mill0(2,ii) + xfft%nft(2)*mill0(3,ii))
     end do
     !
     deallocate(mill0)
     !
References atm_spec::avec, base2357(), atm_spec::bvec, and constant::pi.
Referenced by stdin::read_stdin().
base2357()
subroutine gvec::base2357 (integer, intent(inout) nfft)
Definition at line 115 of file gvec.F90.
     !
     integer,intent(inout) :: nfft
     !
     integer :: base(4) = (/2,3,5,7/), ibase, iexp, &
     &          start, last, nexp, nfft1, nfft2
     !
     start = nfft
     last = 2 * nfft
     !
     do nfft1 = start, last
        !
        nfft2 = nfft1
        !
        do ibase = 1, 4
           !
           nexp = ceiling(log(dble(nfft2))/log(dble(base(ibase))))
           !
           do iexp = 1, nexp
              if(mod(nfft2, base(ibase)) == 0) then
                 nfft2 = nfft2 / base(ibase)
              else
                 exit
              end if
           end do
           !
           if(nfft2 == 1) then
              nfft = nfft1
              return
           end if
           !
        end do
        !
     end do
     !
Referenced by setup_gvec().
Variable Documentation
g_rh
type(fft), save gvec::g_rh
Definition at line 37 of file gvec.F90.
   type(fft),save :: g_rh
Referenced by energy::atomic(), diag_direct::direct(), fftw_wrapper::fft_g2r(), fftw_wrapper::fft_g2r_w(), fftw_wrapper::fft_r2g(), fftw_wrapper::fft_r2g_w(), rho_v::generate_vps(), hamiltonian::h_psi(), energy::hartree(), rho_v::hartree_pot(), fftw_wrapper::init_fft(), rho_v::init_rho_v(), scf::kohn_sham_eq(), k_point::ksum_rho(), pwdft(), griddata::read_griddata(), stdin::read_stdin(), scf::scf_loop(), griddata::write_griddata(), energy::xc(), and rho_v::xc_pot().
g_wf
type(fft), save gvec::g_wf
Definition at line 38 of file gvec.F90.
   type(fft),save :: g_wf
Referenced by diag_direct::direct(), plot::fermi_plot(), fftw_wrapper::fft_g2r_w(), fftw_wrapper::fft_r2g_w(), hamiltonian::h_psi(), fftw_wrapper::init_fft(), scf::initialize_wf(), energy::kinetic(), scf::kohn_sham_eq(), k_point::ksum_rho(), lobpcg::lobpcg_main(), pwdft(), and stdin::read_stdin().