pwdft: hamiltonian Module Reference
hamiltonian Module Reference
Functions/Subroutines
subroutine h_psi (kvec, psi, hpsi)
Function/Subroutine Documentation
h_psi()
subroutine hamiltonian::h_psi (real(8), dimension(3), intent(in) kvec, complex(8), dimension(g_wf%npw,nbnd), intent(in) psi, complex(8), dimension(g_wf%npw,nbnd), intent(out) hpsi)
Definition at line 30 of file hamiltonian.F90.
     !
     use gvec, only : g_wf, g_rh
     use kohn_sham, only : nbnd
     use fftw_wrapper, only : fft_g2r_w, fft_r2g_w
     use rho_v, only : vks
     use atm_spec, only : bvec
     !
     real(8),intent(in) :: kvec(3)
     complex(8),intent(in) :: psi(g_wf%npw,nbnd)
     complex(8),intent(out) :: hpsi(g_wf%npw,nbnd)
     !
     integer :: ipw, ibnd
     real(8) :: kgv(3)
     complex(8) :: psir(g_rh%nr)
     !
     ! Local potential
     !
     do ibnd = 1, nbnd
        call fft_g2r_w(psi(1:g_wf%npw,ibnd), psir)
        psir(1:g_rh%nr) = psir(1:g_rh%nr) * vks(1:g_rh%nr)
        call fft_r2g_w(psir, hpsi(1:g_wf%npw,ibnd))
     end do
     !
     ! Kinetic energy term
     !
     do ipw = 1, g_wf%npw
        kgv(1:3) = kvec(1:3) + matmul(bvec(1:3,1:3), dble(g_wf%mill(1:3,g_wf%map(ipw))))
        hpsi(ipw,1:nbnd) = hpsi(ipw,1:nbnd) &
        &                + 0.5d0 * dot_product(kgv,kgv) * psi(ipw,1:nbnd)
     end do
     !
References atm_spec::bvec, fftw_wrapper::fft_g2r_w(), fftw_wrapper::fft_r2g_w(), gvec::g_rh, gvec::g_wf, kohn_sham::nbnd, and rho_v::vks.
Referenced by lobpcg::lobpcg_main().