pwdft: kohn_sham Module Reference
kohn_sham Module Reference
Variables
character(256), save calculation
Calculation mode.
integer, save nbnd
Number of bands.
real(8), save ef = 0.0d0
Fermi energy [Htr].
real(8), dimension(:,:), allocatable, save eval
(nbnd,nk) Kohn-Sham eigenvalue (energy)
complex(8), dimension(:,:,:), allocatable, save evec
(g_wfnpw,nbnd,nk) Kohn-Sham eigenvector (orbital)
Variable Documentation
calculation
character(256), save kohn_sham::calculation
Calculation mode.
Definition at line 27 of file kohn_sham.F90.
   character(256),save :: &
   & calculation !< Calculation mode
Referenced by scf::kohn_sham_eq(), lobpcg::lobpcg_main(), pwdft(), and stdin::read_stdin().
nbnd
integer, save kohn_sham::nbnd
Number of bands.
Definition at line 29 of file kohn_sham.F90.
   integer,save :: &
   & nbnd !< Number of bands
Referenced by plot::band_plot(), diag_direct::direct(), plot::fermi_plot(), hamiltonian::h_psi(), scf::initialize_wf(), energy::kinetic(), scf::kohn_sham_eq(), k_point::ksum_dos(), k_point::ksum_rho(), lobpcg::lobpcg_main(), pwdft(), pp::read_pp(), and stdin::read_stdin().
ef
real(8), save kohn_sham::ef = 0.0d0
Fermi energy [Htr].
Definition at line 31 of file kohn_sham.F90.
   real(8),save :: &
   & ef = 0.0d0 !< Fermi energy [Htr]
Referenced by plot::band_plot(), plot::fermi_plot(), energy::kinetic(), k_point::ksum_dos(), k_point::ksum_rho(), and pwdft().
eval
real(8), dimension(:,:), allocatable, save kohn_sham::eval
(nbnd,nk) Kohn-Sham eigenvalue (energy)
Definition at line 33 of file kohn_sham.F90.
   real(8),allocatable,save :: &
   & eval(:,:) !< (nbnd,nk) Kohn-Sham eigenvalue (energy)
Referenced by plot::band_plot(), plot::fermi_plot(), energy::kinetic(), scf::kohn_sham_eq(), k_point::ksum_dos(), k_point::ksum_rho(), and pwdft().
evec
complex(8), dimension(:,:,:), allocatable, save kohn_sham::evec
(g_wfnpw,nbnd,nk) Kohn-Sham eigenvector (orbital)
Definition at line 35 of file kohn_sham.F90.
   complex(8),allocatable,save :: &
   & evec(:,:,:) !< (g_wf%npw,nbnd,nk) Kohn-Sham eigenvector (orbital)
Referenced by plot::fermi_plot(), energy::kinetic(), scf::kohn_sham_eq(), k_point::ksum_rho(), and pwdft().