pwdft: fftw_wrapper Module Reference
fftw_wrapper Module Reference
Functions/Subroutines
subroutine init_fft ()
subroutine fft_r2g (VlocR, VlocG)
v(r) e^{-iGr} -> V(G)
subroutine fft_g2r (VlocG, VlocR)
V(G) e^{iGr} -> v(r)
subroutine fft_r2g_w (wfR, wfG)
w(r) e^{-iGr} -> W(G) -> compress
subroutine fft_g2r_w (wfG, wfR)
Uncompress -> W(G) e^{iGr} -> w(r)
Variables
integer, dimension(:), allocatable, save w2r
(g_wfnpw) g_wfnpw -> g_rhnr
Function/Subroutine Documentation
init_fft()
subroutine fftw_wrapper::init_fft
Definition at line 47 of file fftw_wrapper.F90.
     !
     use gvec, only : g_rh, g_wf
     !
     integer :: ipw, igv(3)
     integer(c_int) :: fftwdim(3)
     !
     fftwdim(1:3) = (/g_rh%nft(3), g_rh%nft(2), g_rh%nft(1)/)
     !
     allocate(fft_in(g_rh%nr), fft_out(g_rh%nr))
     !
     plan_g2r = fftw_plan_dft(3, fftwdim, fft_in, fft_out, &
     &                        fftw_backward, fftw_estimate)
     !
     plan_r2g = fftw_plan_dft(3, fftwdim, fft_in, fft_out, &
     &                        fftw_forward, fftw_estimate)
     !
     allocate(w2r(g_wf%npw))
     do ipw = 1, g_wf%npw
        igv(1:3) = g_wf%mill(1:3, g_wf%map(ipw))
        igv(1:3) = modulo(igv(1:3), g_rh%nft(1:3))
        w2r(ipw) = 1 + igv(1) + g_rh%nft(1)*(igv(2) + g_rh%nft(2)*igv(3))
     end do
     !
References gvec::g_rh, gvec::g_wf, and w2r.
Referenced by pwdft().
fft_r2g()
subroutine fftw_wrapper::fft_r2g (real(8), dimension(g_rh%nr), intent(in) VlocR, complex(8), dimension(g_rh%nr), intent(out) VlocG)
v(r) e^{-iGr} -> V(G)
Definition at line 75 of file fftw_wrapper.F90.
     !
     use gvec, only : g_rh
     !
     real(8),intent(in) :: VlocR(g_rh%nr)
     complex(8),intent(out) :: VlocG(g_rh%nr)
     !
     fft_in(1:g_rh%nr) = vlocr(1:g_rh%nr)
     call fftw_execute_dft(plan_r2g, fft_in, fft_out)
     vlocg(1:g_rh%nr) = fft_out(1:g_rh%nr) / dble(g_rh%nr)
     !
References gvec::g_rh.
Referenced by diag_direct::direct(), energy::hartree(), and rho_v::hartree_pot().
fft_g2r()
subroutine fftw_wrapper::fft_g2r (complex(8), dimension(g_rh%nr), intent(in) VlocG, real(8), dimension(g_rh%nr), intent(out) VlocR)
V(G) e^{iGr} -> v(r)
Definition at line 90 of file fftw_wrapper.F90.
     !
     use gvec, only : g_rh
     !
     complex(8),intent(in) :: VlocG(g_rh%nr)
     real(8),intent(out) :: VlocR(g_rh%nr)
     !
     fft_in(1:g_rh%nr) = vlocg(1:g_rh%nr)
     call fftw_execute_dft(plan_g2r, fft_in, fft_out)
     vlocr(1:g_rh%nr) = dble(fft_out(1:g_rh%nr))
     !
References gvec::g_rh.
Referenced by rho_v::generate_vps(), and rho_v::hartree_pot().
fft_r2g_w()
subroutine fftw_wrapper::fft_r2g_w (complex(8), dimension(g_rh%nr), intent(in) wfR, complex(8), dimension(g_wf%npw), intent(out) wfG)
w(r) e^{-iGr} -> W(G) -> compress
Definition at line 105 of file fftw_wrapper.F90.
     !
     use atm_spec, only : vcell
     use gvec, only : g_rh, g_wf
     !
     complex(8),intent(in) :: wfR(g_rh%nr)
     complex(8),intent(out) :: wfG(g_wf%npw)
     !
     fft_in(1:g_rh%nr) = wfr(1:g_rh%nr)
     call fftw_execute_dft(plan_r2g, fft_in, fft_out)
     wfg(1:g_wf%npw) = fft_out(w2r(1:g_wf%npw)) * sqrt(vcell) / dble(g_rh%nr)
     !
References gvec::g_rh, gvec::g_wf, atm_spec::vcell, and w2r.
Referenced by hamiltonian::h_psi().
fft_g2r_w()
subroutine fftw_wrapper::fft_g2r_w (complex(8), dimension(g_wf%npw), intent(in) wfG, complex(8), dimension(g_rh%nr), intent(out) wfR)
Uncompress -> W(G) e^{iGr} -> w(r)
Definition at line 121 of file fftw_wrapper.F90.
     !
     use atm_spec, only : vcell
     use gvec, only : g_rh, g_wf
     !
     complex(8),intent(in) :: wfG(g_wf%npw)
     complex(8),intent(out) :: wfR(g_rh%nr)
     !
     fft_in(1:g_rh%nr) = 0.0d0
     fft_in(w2r(1:g_wf%npw)) = wfg(1:g_wf%npw)
     call fftw_execute_dft(plan_g2r, fft_in, fft_out)
     wfr(1:g_rh%nr) = fft_out(1:g_rh%nr) / sqrt(vcell)
     !
References gvec::g_rh, gvec::g_wf, atm_spec::vcell, and w2r.
Referenced by hamiltonian::h_psi(), and k_point::ksum_rho().
Variable Documentation
w2r
integer, dimension(:), allocatable, save fftw_wrapper::w2r
(g_wfnpw) g_wfnpw -> g_rhnr
Definition at line 35 of file fftw_wrapper.F90.
   integer,allocatable,save :: &
   & w2r(:) !< (g_wf%npw) g_wf%npw -> g_rh%nr
Referenced by fft_g2r_w(), fft_r2g_w(), and init_fft().