pwdft: libtetrabz_common Module Reference
libtetrabz_common Module Reference
Functions/Subroutines
subroutine, public libtetrabz_initialize (ltetra, nge, ngw, bvec, linterpol, wlsm, nk_local, nt_local, nkBZ, ik_global, ik_local, kvec, comm)
subroutine, public libtetrabz_sort (n, key, indx)
subroutine, public libtetrabz_interpol_indx (ng, kvec, kintp, wintp)
subroutine, public libtetrabz_tsmall_a1 (e, V, tsmall)
subroutine, public libtetrabz_tsmall_b1 (e, V, tsmall)
subroutine, public libtetrabz_tsmall_b2 (e, V, tsmall)
subroutine, public libtetrabz_tsmall_b3 (e, V, tsmall)
subroutine, public libtetrabz_tsmall_c1 (e, V, tsmall)
subroutine, public libtetrabz_tsmall_c2 (e, V, tsmall)
subroutine, public libtetrabz_tsmall_c3 (e, V, tsmall)
subroutine, public libtetrabz_triangle_a1 (e, V, tsmall)
subroutine, public libtetrabz_triangle_b1 (e, V, tsmall)
subroutine, public libtetrabz_triangle_b2 (e, V, tsmall)
subroutine, public libtetrabz_triangle_c1 (e, V, tsmall)
subroutine, public libtetrabz_mpisum_d (comm, scaler)
subroutine, public libtetrabz_mpisum_dv (comm, ndim, vector)
subroutine, public libtetrabz_mpisum_zv (comm, ndim, vector)
Function/Subroutine Documentation
libtetrabz_initialize()
subroutine, public libtetrabz_common::libtetrabz_initialize (integer, intent(in) ltetra, integer, dimension(3), intent(in) nge, integer, dimension(3), intent(in) ngw, real(8), dimension(3,3), intent(in) bvec, logical, intent(out) linterpol, real(8), dimension(4,20), intent(out) wlsm, integer, intent(out) nk_local, integer, intent(out) nt_local, integer, intent(out) nkBZ, integer, dimension(:,:), intent(out), allocatable ik_global, integer, dimension(:,:), intent(out), allocatable ik_local, real(8), dimension(:,:), intent(out), allocatable kvec, integer, intent(in), optional comm)
Definition at line 40 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   INTEGER,INTENT(IN) :: ltetra, nge(3), ngw(3)
   REAL(8),INTENT(IN) :: bvec(3,3)
   LOGICAL,INTENT(OUT) :: linterpol
   REAL(8),INTENT(OUT) :: wlsm(4,20)
   INTEGER,INTENT(OUT) :: nk_local, nt_local, nkBZ
   INTEGER,INTENT(OUT),ALLOCATABLE :: ik_global(:,:), ik_local(:,:)
   REAL(8),INTENT(OUT),ALLOCATABLE :: kvec(:,:)
   INTEGER,INTENT(IN),OPTIONAL :: comm
   !
   INTEGER :: itype, i1, i2, i3, it, divvec(4,4), ivvec0(4), ivvec(3,20,6)
   REAL(8) :: l(4), bvec2(3,3), bvec3(3,4)
   !
   nkbz = product(nge(1:3))
   linterpol = .NOT. all(nge(1:3) == ngw(1:3))
   !
   DO i1 = 1, 3
      bvec2(1:3,i1) = bvec(1:3,i1) / dble(nge(i1))
   END DO
   !
   bvec3(1:3,1) = -bvec2(1:3,1) + bvec2(1:3,2) + bvec2(1:3,3)
   bvec3(1:3,2) =  bvec2(1:3,1) - bvec2(1:3,2) + bvec2(1:3,3)
   bvec3(1:3,3) =  bvec2(1:3,1) + bvec2(1:3,2) - bvec2(1:3,3)
   bvec3(1:3,4) =  bvec2(1:3,1) + bvec2(1:3,2) + bvec2(1:3,3)
   !
   ! length of delta bvec
   !
   DO i1 = 1, 4
      l(i1) = dot_product(bvec3(1:3,i1),bvec3(1:3,i1))
   END DO
   !
   itype = minloc(l(1:4),1)
   !
   ! start & last
   !
   ivvec0(1:4) = (/ 0, 0, 0, 0 /)
   !
   divvec(1:4,1) = (/ 1, 0, 0, 0 /)
   divvec(1:4,2) = (/ 0, 1, 0, 0 /)
   divvec(1:4,3) = (/ 0, 0, 1, 0 /)
   divvec(1:4,4) = (/ 0, 0, 0, 1 /)
   !
   ivvec0(itype) = 1
   divvec(itype, itype) = - 1
   !
   ! Corners of tetrahedra
   !
   it = 0
   DO i1 = 1, 3
      DO i2 = 1, 3
         IF(i2 == i1) cycle
         DO i3 = 1, 3
            IF(i3 == i1 .OR. i3 == i2) cycle
            !
            it = it + 1
            !
            ivvec(1:3,1,it) = ivvec0(1:3)
            ivvec(1:3,2,it) = ivvec(1:3,1,it) + divvec(1:3,i1)
            ivvec(1:3,3,it) = ivvec(1:3,2,it) + divvec(1:3,i2)
            ivvec(1:3,4,it) = ivvec(1:3,3,it) + divvec(1:3,i3)
            !
         END DO
      END DO
   END DO
   !
   ! Additional points
   !
   ivvec(1:3, 5,1:6) = 2 * ivvec(1:3,1,1:6) - ivvec(1:3,2,1:6)
   ivvec(1:3, 6,1:6) = 2 * ivvec(1:3,2,1:6) - ivvec(1:3,3,1:6)
   ivvec(1:3, 7,1:6) = 2 * ivvec(1:3,3,1:6) - ivvec(1:3,4,1:6)
   ivvec(1:3, 8,1:6) = 2 * ivvec(1:3,4,1:6) - ivvec(1:3,1,1:6)
   !
   ivvec(1:3, 9,1:6) = 2 * ivvec(1:3,1,1:6) - ivvec(1:3,3,1:6)
   ivvec(1:3,10,1:6) = 2 * ivvec(1:3,2,1:6) - ivvec(1:3,4,1:6)
   ivvec(1:3,11,1:6) = 2 * ivvec(1:3,3,1:6) - ivvec(1:3,1,1:6)
   ivvec(1:3,12,1:6) = 2 * ivvec(1:3,4,1:6) - ivvec(1:3,2,1:6)
   !
   ivvec(1:3,13,1:6) = 2 * ivvec(1:3,1,1:6) - ivvec(1:3,4,1:6)
   ivvec(1:3,14,1:6) = 2 * ivvec(1:3,2,1:6) - ivvec(1:3,1,1:6)
   ivvec(1:3,15,1:6) = 2 * ivvec(1:3,3,1:6) - ivvec(1:3,2,1:6)
   ivvec(1:3,16,1:6) = 2 * ivvec(1:3,4,1:6) - ivvec(1:3,3,1:6)
   !
   ivvec(1:3,17,1:6) =  ivvec(1:3,4,1:6) - ivvec(1:3,1,1:6) + ivvec(1:3,2,1:6)
   ivvec(1:3,18,1:6) =  ivvec(1:3,1,1:6) - ivvec(1:3,2,1:6) + ivvec(1:3,3,1:6)
   ivvec(1:3,19,1:6) =  ivvec(1:3,2,1:6) - ivvec(1:3,3,1:6) + ivvec(1:3,4,1:6)
   ivvec(1:3,20,1:6) =  ivvec(1:3,3,1:6) - ivvec(1:3,4,1:6) + ivvec(1:3,1,1:6)
   !
   IF(ltetra == 1) THEN
      !
      !WRITE(*,*) "[libtetrabz] Linear tetrahedron method is used."
      !
      wlsm(1:4,1:20) = 0.0d0
      wlsm(1,1) = 1.0d0
      wlsm(2,2) = 1.0d0
      wlsm(3,3) = 1.0d0
      wlsm(4,4) = 1.0d0
      !
   ELSE IF(ltetra == 2) THEN
      !
      !WRITE(*,*) "[libtetrabz] Improved tetrahedron method is used."
      !
      wlsm(1, 1: 4) = dble((/1440,    0,   30,    0/))
      wlsm(2, 1: 4) = dble((/   0, 1440,    0,   30/))
      wlsm(3, 1: 4) = dble((/  30,    0, 1440,    0/))
      wlsm(4, 1: 4) = dble((/   0,   30,    0, 1440/))
      !
      wlsm(1, 5: 8) = dble((/ -38,    7,   17,  -28/))
      wlsm(2, 5: 8) = dble((/ -28,  -38,    7,   17/))
      wlsm(3, 5: 8) = dble((/  17,  -28,  -38,    7/))
      wlsm(4, 5: 8) = dble((/   7,   17,  -28,  -38/))
      !
      wlsm(1, 9:12) = dble((/ -56,    9,  -46,    9/))
      wlsm(2, 9:12) = dble((/   9,  -56,    9,  -46/))
      wlsm(3, 9:12) = dble((/ -46,    9,  -56,    9/))
      wlsm(4, 9:12) = dble((/   9,  -46,    9,  -56/))
      !
      wlsm(1,13:16) = dble((/ -38,  -28,   17,    7/))
      wlsm(2,13:16) = dble((/   7,  -38,  -28,   17/))
      wlsm(3,13:16) = dble((/  17,    7,  -38,  -28/))
      wlsm(4,13:16) = dble((/ -28,   17,    7,  -38/))
      !
      wlsm(1,17:20) = dble((/ -18,  -18,   12,  -18/))
      wlsm(2,17:20) = dble((/ -18,  -18,  -18,   12/))
      wlsm(3,17:20) = dble((/  12,  -18,  -18,  -18/))
      wlsm(4,17:20) = dble((/ -18,   12,  -18,  -18/))
      !
      wlsm(1:4,1:20) = wlsm(1:4,1:20) / 1260d0
      !
   ELSE
      !
      WRITE(*,*) "[libtetrabz] STOP! ltetrta is invalid."
      stop
      !
   END IF
   !
   IF (PRESENT(comm)) THEN
      CALL libtetrabz_kgrid(linterpol,ivvec,nge,nkbz,nk_local,nt_local,ik_global,ik_local,kvec,comm)
   ELSE
      CALL libtetrabz_kgrid(linterpol,ivvec,nge,nkbz,nk_local,nt_local,ik_global,ik_local,kvec)
   END IF
   !
Referenced by libtetrabz_dbldelta_mod::libtetrabz_dbldelta(), libtetrabz_dblstep_mod::libtetrabz_dblstep(), libtetrabz_dos_mod::libtetrabz_dos(), libtetrabz_occ_mod::libtetrabz_fermieng(), libtetrabz_fermigr_mod::libtetrabz_fermigr(), libtetrabz_dos_mod::libtetrabz_intdos(), libtetrabz_occ_mod::libtetrabz_occ(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx(), and libtetrabz_polstat_mod::libtetrabz_polstat().
libtetrabz_sort()
subroutine, public libtetrabz_common::libtetrabz_sort (integer, intent(in) n, real(8), dimension(n), intent(inout) key, integer, dimension(n), intent(out) indx)
Definition at line 308 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   integer,INTENT(IN) :: n
   REAL(8),INTENT(inout) :: key(n)
   INTEGER,INTENT(OUT) :: indx(n)
   !
   INTEGER :: i, i0, indx0
   REAL(8) :: key0
   !
   DO i = 1, n
      indx(i) = i
   END DO
   !
   DO i = 1, n - 1
      key0 = minval(key(i+1:n))
      i0   = minloc(key(i+1:n),1) + i
      IF(key(i) > key0) THEN
         key(i0) = key(i)
         key(i) = key0
         !
         indx0 = indx(i0)
         indx(i0) = indx(i)
         indx(i) = indx0
      END IF
   END DO
   !
Referenced by libtetrabz_dbldelta_mod::libtetrabz_dbldelta2(), libtetrabz_dbldelta_mod::libtetrabz_dbldelta_main(), libtetrabz_dblstep_mod::libtetrabz_dblstep2(), libtetrabz_dblstep_mod::libtetrabz_dblstep_main(), libtetrabz_dos_mod::libtetrabz_dos_main(), libtetrabz_fermigr_mod::libtetrabz_fermigr2(), libtetrabz_fermigr_mod::libtetrabz_fermigr3(), libtetrabz_fermigr_mod::libtetrabz_fermigr_main(), libtetrabz_dos_mod::libtetrabz_intdos_main(), libtetrabz_occ_mod::libtetrabz_occ_main(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx2(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx3(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx_main(), libtetrabz_polstat_mod::libtetrabz_polstat2(), libtetrabz_polstat_mod::libtetrabz_polstat3(), and libtetrabz_polstat_mod::libtetrabz_polstat_main().
libtetrabz_interpol_indx()
subroutine, public libtetrabz_common::libtetrabz_interpol_indx (integer, dimension(3), intent(in) ng, real(8), dimension(3), intent(in) kvec, integer, dimension(8), intent(out) kintp, real(8), dimension(8), intent(out) wintp)
Definition at line 340 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   INTEGER,INTENT(in) :: ng(3)
   REAL(8),INTENT(in) :: kvec(3)
   INTEGER,INTENT(out) :: kintp(8)
   REAL(8),INTENT(out) :: wintp(8)
   !
   INTEGER :: ii
   REAL(8) :: xv(3)
   integer :: ikv0(3), ikv1(3), i1, i2, i3
   !
   xv(1:3) = kvec(1:3) * dble(ng(1:3))
   ikv0(1:3) = floor(xv(1:3))
   xv(1:3) = xv(1:3) - dble(ikv0(1:3))
   !
   ii = 0
   DO i1 = 0, 1
      DO i2 = 0, 1
         DO i3 = 0, 1
            !
            ii = ii + 1
            !
            ikv1(1:3) = ikv0(1:3) + (/i1, i2, i3/)
            ikv1(1:3) = modulo(ikv1(1:3), ng(1:3))
            kintp(ii) = 1 + ikv1(1) + ng(1) * ikv1(2) + ng(1) * ng(2) * ikv1(3)
            !
            wintp(ii) = xv(1)**i1 * (1.0d0 - xv(1))**(1 - i1) &
            &         * xv(2)**i2 * (1.0d0 - xv(2))**(1 - i2) &
            &         * xv(3)**i3 * (1.0d0 - xv(3))**(1 - i3)
            !
         END DO
      END DO
   END DO
   !
Referenced by libtetrabz_dbldelta_mod::libtetrabz_dbldelta(), libtetrabz_dblstep_mod::libtetrabz_dblstep(), libtetrabz_dos_mod::libtetrabz_dos(), libtetrabz_occ_mod::libtetrabz_fermieng(), libtetrabz_fermigr_mod::libtetrabz_fermigr(), libtetrabz_dos_mod::libtetrabz_intdos(), libtetrabz_occ_mod::libtetrabz_occ(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx(), and libtetrabz_polstat_mod::libtetrabz_polstat().
libtetrabz_tsmall_a1()
subroutine, public libtetrabz_common::libtetrabz_tsmall_a1 (real(8), dimension(4), intent(in) e, real(8), intent(out) V, real(8), dimension(4,4), intent(out) tsmall)
Definition at line 380 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   REAL(8),INTENT(IN) :: e(4)
   REAL(8),INTENT(OUT) :: V
   REAL(8),INTENT(OUT) :: tsmall(4,4)
   !
   INTEGER :: ii
   REAL(8) :: a(4,4)
   !
   DO ii = 1, 4
      a(1:4,ii) = (0d0 - e(ii)) / (e(1:4) - e(ii))
   END DO
   !
   v = a(2,1) * a(3,1) * a(4,1)
   !
   tsmall(1, 1:4) = (/   1d0,    0d0,    0d0,    0d0/)
   tsmall(2, 1:4) = (/a(1,2), a(2,1),    0d0,    0d0/)
   tsmall(3, 1:4) = (/a(1,3),    0d0, a(3,1),    0d0/)
   tsmall(4, 1:4) = (/a(1,4),    0d0,    0d0, a(4,1)/)
   !
Referenced by libtetrabz_dblstep_mod::libtetrabz_dblstep2(), libtetrabz_dblstep_mod::libtetrabz_dblstep_main(), libtetrabz_fermigr_mod::libtetrabz_fermigr2(), libtetrabz_fermigr_mod::libtetrabz_fermigr_main(), libtetrabz_dos_mod::libtetrabz_intdos_main(), libtetrabz_occ_mod::libtetrabz_occ_main(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx2(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx_main(), libtetrabz_polstat_mod::libtetrabz_polstat2(), and libtetrabz_polstat_mod::libtetrabz_polstat_main().
libtetrabz_tsmall_b1()
subroutine, public libtetrabz_common::libtetrabz_tsmall_b1 (real(8), dimension(4), intent(in) e, real(8), intent(out) V, real(8), dimension(4,4), intent(out) tsmall)
Definition at line 406 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   REAL(8),INTENT(IN) :: e(4)
   REAL(8),INTENT(OUT) :: V
   REAL(8),INTENT(OUT) :: tsmall(4,4)
   !
   INTEGER :: ii
   REAL(8) :: a(4,4)
   !
   DO ii = 1, 4
      a(1:4,ii) = (0d0 - e(ii)) / (e(1:4) - e(ii))
   END DO
   !
   v = a(3,1) * a(4,1) * a(2,4)
   !
   tsmall(1, 1:4) = (/   1d0,    0d0,    0d0,    0d0/)
   tsmall(2, 1:4) = (/a(1,3),    0d0, a(3,1),    0d0/)
   tsmall(3, 1:4) = (/a(1,4),    0d0,    0d0, a(4,1)/)
   tsmall(4, 1:4) = (/   0d0, a(2,4),    0d0, a(4,2)/)
   !
Referenced by libtetrabz_dblstep_mod::libtetrabz_dblstep2(), libtetrabz_dblstep_mod::libtetrabz_dblstep_main(), libtetrabz_fermigr_mod::libtetrabz_fermigr2(), libtetrabz_fermigr_mod::libtetrabz_fermigr_main(), libtetrabz_dos_mod::libtetrabz_intdos_main(), libtetrabz_occ_mod::libtetrabz_occ_main(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx2(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx_main(), libtetrabz_polstat_mod::libtetrabz_polstat2(), and libtetrabz_polstat_mod::libtetrabz_polstat_main().
libtetrabz_tsmall_b2()
subroutine, public libtetrabz_common::libtetrabz_tsmall_b2 (real(8), dimension(4), intent(in) e, real(8), intent(out) V, real(8), dimension(4,4), intent(out) tsmall)
Definition at line 432 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   REAL(8),INTENT(IN) :: e(4)
   REAL(8),INTENT(OUT) :: V
   REAL(8),INTENT(OUT) :: tsmall(4,4)
   !
   INTEGER :: ii
   REAL(8) :: a(4,4)
   !
   DO ii = 1, 4
      a(1:4,ii) = (0d0 - e(ii)) / (e(1:4) - e(ii))
   END DO
   !
   v = a(3,2) * a(4,2)
   !
   tsmall(1, 1:4) = (/1d0,    0d0,    0d0,    0d0/)
   tsmall(2, 1:4) = (/0d0,    1d0,    0d0,    0d0/)
   tsmall(3, 1:4) = (/0d0, a(2,3), a(3,2),    0d0/)
   tsmall(4, 1:4) = (/0d0, a(2,4),    0d0, a(4,2)/)
   !
Referenced by libtetrabz_dblstep_mod::libtetrabz_dblstep2(), libtetrabz_dblstep_mod::libtetrabz_dblstep_main(), libtetrabz_fermigr_mod::libtetrabz_fermigr2(), libtetrabz_fermigr_mod::libtetrabz_fermigr_main(), libtetrabz_dos_mod::libtetrabz_intdos_main(), libtetrabz_occ_mod::libtetrabz_occ_main(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx2(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx_main(), libtetrabz_polstat_mod::libtetrabz_polstat2(), and libtetrabz_polstat_mod::libtetrabz_polstat_main().
libtetrabz_tsmall_b3()
subroutine, public libtetrabz_common::libtetrabz_tsmall_b3 (real(8), dimension(4), intent(in) e, real(8), intent(out) V, real(8), dimension(4,4), intent(out) tsmall)
Definition at line 458 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   REAL(8),INTENT(IN) :: e(4)
   REAL(8),INTENT(OUT) :: V
   REAL(8),INTENT(OUT) :: tsmall(4,4)
   !
   INTEGER :: ii
   REAL(8) :: a(4,4)
   !
   DO ii = 1, 4
      a(1:4,ii) = (0d0 - e(ii)) / (e(1:4) - e(ii))
   END DO
   !
   v = a(2,3) * a(3,1) * a(4,2)
   !
   tsmall(1, 1:4) = (/   1d0,    0d0,    0d0,    0d0/)
   tsmall(2, 1:4) = (/a(1,3),    0d0, a(3,1),    0d0/)
   tsmall(3, 1:4) = (/   0d0, a(2,3), a(3,2),    0d0/)
   tsmall(4, 1:4) = (/   0d0, a(2,4),    0d0, a(4,2)/)
   !
Referenced by libtetrabz_dblstep_mod::libtetrabz_dblstep2(), libtetrabz_dblstep_mod::libtetrabz_dblstep_main(), libtetrabz_fermigr_mod::libtetrabz_fermigr2(), libtetrabz_fermigr_mod::libtetrabz_fermigr_main(), libtetrabz_dos_mod::libtetrabz_intdos_main(), libtetrabz_occ_mod::libtetrabz_occ_main(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx2(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx_main(), libtetrabz_polstat_mod::libtetrabz_polstat2(), and libtetrabz_polstat_mod::libtetrabz_polstat_main().
libtetrabz_tsmall_c1()
subroutine, public libtetrabz_common::libtetrabz_tsmall_c1 (real(8), dimension(4), intent(in) e, real(8), intent(out) V, real(8), dimension(4,4), intent(out) tsmall)
Definition at line 484 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   REAL(8),INTENT(IN) :: e(4)
   REAL(8),INTENT(OUT) :: V
   REAL(8),INTENT(OUT) :: tsmall(4,4)
   !
   INTEGER :: ii
   REAL(8) :: a(4,4)
   !
   DO ii = 1, 4
      a(1:4,ii) = (0d0 - e(ii)) / (e(1:4) - e(ii))
   END DO
   !
   v = a(4,3)
   !
   tsmall(1, 1:4) = (/1d0, 0d0,    0d0,    0d0/)
   tsmall(2, 1:4) = (/0d0, 1d0,    0d0,    0d0/)
   tsmall(3, 1:4) = (/0d0, 0d0,    1d0,    0d0/)
   tsmall(4, 1:4) = (/0d0, 0d0, a(3,4), a(4,3)/)
   !
Referenced by libtetrabz_dblstep_mod::libtetrabz_dblstep2(), libtetrabz_dblstep_mod::libtetrabz_dblstep_main(), libtetrabz_fermigr_mod::libtetrabz_fermigr2(), libtetrabz_fermigr_mod::libtetrabz_fermigr_main(), libtetrabz_dos_mod::libtetrabz_intdos_main(), libtetrabz_occ_mod::libtetrabz_occ_main(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx2(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx_main(), libtetrabz_polstat_mod::libtetrabz_polstat2(), and libtetrabz_polstat_mod::libtetrabz_polstat_main().
libtetrabz_tsmall_c2()
subroutine, public libtetrabz_common::libtetrabz_tsmall_c2 (real(8), dimension(4), intent(in) e, real(8), intent(out) V, real(8), dimension(4,4), intent(out) tsmall)
Definition at line 510 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   REAL(8),INTENT(IN) :: e(4)
   REAL(8),INTENT(OUT) :: V
   REAL(8),INTENT(OUT) :: tsmall(4,4)
   !
   INTEGER :: ii
   REAL(8) :: a(4,4)
   !
   DO ii = 1, 4
      a(1:4,ii) = (0d0 - e(ii)) / (e(1:4) - e(ii))
   END DO
   !
   v = a(3,4) * a(4,2)
   !
   tsmall(1, 1:4) = (/1d0,    0d0,    0d0,    0d0/)
   tsmall(2, 1:4) = (/0d0,    1d0,    0d0,    0d0/)
   tsmall(3, 1:4) = (/0d0, a(2,4),    0d0, a(4,2)/)
   tsmall(4, 1:4) = (/0d0,    0d0, a(3,4), a(4,3)/)
   !
Referenced by libtetrabz_dblstep_mod::libtetrabz_dblstep2(), libtetrabz_dblstep_mod::libtetrabz_dblstep_main(), libtetrabz_fermigr_mod::libtetrabz_fermigr2(), libtetrabz_fermigr_mod::libtetrabz_fermigr_main(), libtetrabz_dos_mod::libtetrabz_intdos_main(), libtetrabz_occ_mod::libtetrabz_occ_main(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx2(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx_main(), libtetrabz_polstat_mod::libtetrabz_polstat2(), and libtetrabz_polstat_mod::libtetrabz_polstat_main().
libtetrabz_tsmall_c3()
subroutine, public libtetrabz_common::libtetrabz_tsmall_c3 (real(8), dimension(4), intent(in) e, real(8), intent(out) V, real(8), dimension(4,4), intent(out) tsmall)
Definition at line 536 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   REAL(8),INTENT(IN) :: e(4)
   REAL(8),INTENT(OUT) :: V
   REAL(8),INTENT(OUT) :: tsmall(4,4)
   !
   INTEGER :: ii
   REAL(8) :: a(4,4)
   !
   DO ii = 1, 4
      a(1:4,ii) = (0d0 - e(ii)) / (e(1:4) - e(ii))
   END DO
   !
   v = a(3,4) * a(2,4) * a(4,1)
   !
   tsmall(1, 1:4) = (/   1d0,    0d0,    0d0,    0d0/)
   tsmall(2, 1:4) = (/a(1,4),    0d0,    0d0, a(4,1)/)
   tsmall(3, 1:4) = (/   0d0, a(2,4),    0d0, a(4,2)/)
   tsmall(4, 1:4) = (/   0d0,    0d0, a(3,4), a(4,3)/)
   !
Referenced by libtetrabz_dblstep_mod::libtetrabz_dblstep2(), libtetrabz_dblstep_mod::libtetrabz_dblstep_main(), libtetrabz_fermigr_mod::libtetrabz_fermigr2(), libtetrabz_fermigr_mod::libtetrabz_fermigr_main(), libtetrabz_dos_mod::libtetrabz_intdos_main(), libtetrabz_occ_mod::libtetrabz_occ_main(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx2(), libtetrabz_polcmplx_mod::libtetrabz_polcmplx_main(), libtetrabz_polstat_mod::libtetrabz_polstat2(), and libtetrabz_polstat_mod::libtetrabz_polstat_main().
libtetrabz_triangle_a1()
subroutine, public libtetrabz_common::libtetrabz_triangle_a1 (real(8), dimension(4), intent(in) e, real(8), intent(out) V, real(8), dimension(3,4), intent(out) tsmall)
Definition at line 562 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   REAL(8),INTENT(IN) :: e(4)
   REAL(8),INTENT(OUT) :: V
   REAL(8),INTENT(OUT) :: tsmall(3,4)
   !
   INTEGER :: ii
   REAL(8) :: a(4,4)
   !
   DO ii = 1, 4
      a(1:4,ii) = (0d0 - e(ii)) / (e(1:4) - e(ii))
   END DO
   !
   !V = 3d0 * a(2,1) * a(3,1) * a(4,1) / (0d0 - e(1))
   v = 3d0 * a(2,1) * a(3,1)           / (e(4) - e(1))
   !
   tsmall(1,1:4) = (/a(1,2), a(2,1),    0d0,    0d0/)
   tsmall(2,1:4) = (/a(1,3),    0d0, a(3,1),    0d0/)
   tsmall(3,1:4) = (/a(1,4),    0d0,    0d0, a(4,1)/)
   !
Referenced by libtetrabz_dbldelta_mod::libtetrabz_dbldelta_main(), libtetrabz_dos_mod::libtetrabz_dos_main(), and libtetrabz_fermigr_mod::libtetrabz_fermigr3().
libtetrabz_triangle_b1()
subroutine, public libtetrabz_common::libtetrabz_triangle_b1 (real(8), dimension(4), intent(in) e, real(8), intent(out) V, real(8), dimension(3,4), intent(out) tsmall)
Definition at line 588 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   REAL(8),INTENT(IN) :: e(4)
   REAL(8),INTENT(OUT) :: V
   REAL(8),INTENT(OUT) :: tsmall(3,4)
   !
   INTEGER :: ii
   REAL(8) :: a(4,4)
   !
   DO ii = 1, 4
      a(1:4,ii) = (0d0 - e(ii)) / (e(1:4) - e(ii))
   END DO
   !
   !V = 3d0 * a(3,1) * a(4,1) * a(2,4) / (0d0 - e(1))
   v = 3d0           * a(4,1) * a(2,4) / (e(3) - e(1))
   !
   tsmall(1,1:4) = (/a(1,3),    0d0, a(3,1),    0d0/)
   tsmall(2,1:4) = (/a(1,4),    0d0,    0d0, a(4,1)/)
   tsmall(3,1:4) = (/   0d0, a(2,4),    0d0, a(4,2)/)
   !
Referenced by libtetrabz_dbldelta_mod::libtetrabz_dbldelta_main(), libtetrabz_dos_mod::libtetrabz_dos_main(), and libtetrabz_fermigr_mod::libtetrabz_fermigr3().
libtetrabz_triangle_b2()
subroutine, public libtetrabz_common::libtetrabz_triangle_b2 (real(8), dimension(4), intent(in) e, real(8), intent(out) V, real(8), dimension(3,4), intent(out) tsmall)
Definition at line 614 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   REAL(8),INTENT(IN) :: e(4)
   REAL(8),INTENT(OUT) :: V
   REAL(8),INTENT(OUT) :: tsmall(3,4)
   !
   INTEGER :: ii
   REAL(8) :: a(4,4)
   !
   DO ii = 1, 4
      a(1:4,ii) = (0d0 - e(ii)) / (e(1:4) - e(ii))
   END DO
   !
   !V = 3d0 * a(2,3) * a(3,1) * a(4,2) / (0d0 - e(1))
   v = 3d0 * a(2,3)           * a(4,2) / (e(3) - e(1))
   !
   tsmall(1,1:4) = (/a(1,3),    0d0, a(3,1),    0d0/)
   tsmall(2,1:4) = (/   0d0, a(2,3), a(3,2),    0d0/)
   tsmall(3,1:4) = (/   0d0, a(2,4),    0d0, a(4,2)/)
   !
Referenced by libtetrabz_dbldelta_mod::libtetrabz_dbldelta_main(), libtetrabz_dos_mod::libtetrabz_dos_main(), and libtetrabz_fermigr_mod::libtetrabz_fermigr3().
libtetrabz_triangle_c1()
subroutine, public libtetrabz_common::libtetrabz_triangle_c1 (real(8), dimension(4), intent(in) e, real(8), intent(out) V, real(8), dimension(3,4), intent(out) tsmall)
Definition at line 640 of file libtetrabz_common.F90.
   !
   IMPLICIT NONE
   !
   REAL(8),INTENT(IN) :: e(4)
   REAL(8),INTENT(OUT) :: V
   REAL(8),INTENT(OUT) :: tsmall(3,4)
   !
   INTEGER :: ii
   REAL(8) :: a(4,4)
   !
   DO ii = 1, 4
      a(1:4,ii) = (0d0 - e(ii)) / (e(1:4) - e(ii))
   END DO
   !
   !V = 3d0 * a(1,4) * a(2,4) * a(3,4) / (e(4) - 0d0)
   v = 3d0 * a(1,4) * a(2,4)           / (e(4) - e(3))
   !
   tsmall(1,1:4) = (/a(1,4),    0d0,    0d0, a(4,1)/)
   tsmall(2,1:4) = (/   0d0, a(2,4),    0d0, a(4,2)/)
   tsmall(3,1:4) = (/   0d0,    0d0, a(3,4), a(4,3)/)
   !
Referenced by libtetrabz_dbldelta_mod::libtetrabz_dbldelta_main(), libtetrabz_dos_mod::libtetrabz_dos_main(), and libtetrabz_fermigr_mod::libtetrabz_fermigr3().
libtetrabz_mpisum_d()
subroutine, public libtetrabz_common::libtetrabz_mpisum_d (integer comm, real(8) scaler)
Definition at line 666 of file libtetrabz_common.F90.
   !
 #if defined(__MPI)
   USE mpi, ONLY : mpi_double_precision, mpi_in_place, mpi_sum
 #endif
   IMPLICIT NONE
   !
   INTEGER :: comm
   REAL(8) :: scaler
   !
 #if defined(__MPI)
   INTEGER :: ierr
   !
   CALL mpi_allreduce(mpi_in_place, scaler, 1, &
   &                  mpi_double_precision, mpi_sum, comm, ierr)
 #endif
   !
Referenced by libtetrabz_occ_mod::libtetrabz_fermieng().
libtetrabz_mpisum_dv()
subroutine, public libtetrabz_common::libtetrabz_mpisum_dv (integer comm, integer ndim, real(8), dimension(ndim) vector)
Definition at line 687 of file libtetrabz_common.F90.
   !
 #if defined(__MPI)
   USE mpi, ONLY : mpi_double_precision, mpi_in_place, mpi_sum
 #endif
   IMPLICIT NONE
   !
   INTEGER :: comm, ndim
   REAL(8) :: vector(ndim)
   !
 #if defined(__MPI)
   INTEGER :: ierr
   !
   CALL mpi_allreduce(mpi_in_place, vector, ndim, &
   &                  mpi_double_precision, mpi_sum, comm, ierr)
 #endif
   !
Referenced by libtetrabz_dbldelta_mod::libtetrabz_dbldelta(), libtetrabz_dblstep_mod::libtetrabz_dblstep(), libtetrabz_dos_mod::libtetrabz_dos(), libtetrabz_occ_mod::libtetrabz_fermieng(), libtetrabz_fermigr_mod::libtetrabz_fermigr(), libtetrabz_dos_mod::libtetrabz_intdos(), libtetrabz_occ_mod::libtetrabz_occ(), and libtetrabz_polstat_mod::libtetrabz_polstat().
libtetrabz_mpisum_zv()
subroutine, public libtetrabz_common::libtetrabz_mpisum_zv (integer comm, integer ndim, complex(8), dimension(ndim) vector)
Definition at line 708 of file libtetrabz_common.F90.
   !
 #if defined(__MPI)
   USE mpi, ONLY : mpi_double_complex, mpi_in_place, mpi_sum
 #endif
   IMPLICIT NONE
   !
   INTEGER :: comm, ndim
   COMPLEX(8) :: vector(ndim)
   !
 #if defined(__MPI)
   INTEGER :: ierr
   !
   CALL mpi_allreduce(mpi_in_place, vector, ndim, &
   &                  mpi_double_complex, mpi_sum, comm, ierr)
 #endif
   !
Referenced by libtetrabz_polcmplx_mod::libtetrabz_polcmplx().