pwdft: atm_spec Module Reference
atm_spec Module Reference
Data Types
type atm_t
type spec_t
Variables
integer, save nat
Number of atoms.
integer, save ntyp
Number of species (elements)
real(8), save vcell
Unit cell volume [Bohr^3].
real(8), save nelec
Number of electrons per u.c.
real(8), dimension(3, 3), save avec
Unit lattice vector [Bohr].
real(8), dimension(3, 3), save bvec
Unit reciplocal lattice vector [Bohr^-1].
type(atm_t), dimension(:), allocatable, save atm
(nat) Atom
type(spec_t), dimension(:), allocatable, save spec
(ntyp) Species
Variable Documentation
nat
integer, save atm_spec::nat
Number of atoms.
Definition at line 47 of file atm_spec.F90.
   integer,save :: &
   & nat, &  !< Number of atoms
   & ntyp !< Number of species (elements)
Referenced by energy::ewald(), rho_v::generate_vps(), griddata::read_griddata(), pp::read_pp(), stdin::read_stdin(), and griddata::write_griddata().
ntyp
integer, save atm_spec::ntyp
Number of species (elements)
Definition at line 47 of file atm_spec.F90.
Referenced by rho_v::generate_vps(), pp::read_pp(), and stdin::read_stdin().
vcell
real(8), save atm_spec::vcell
Unit cell volume [Bohr^3].
Definition at line 50 of file atm_spec.F90.
   real(8),save :: &
   & Vcell, & !< Unit cell volume [Bohr^3]
   & nelec, & !< Number of electrons per u.c.
   & avec(3,3), & !< Unit lattice vector [Bohr]
   & bvec(3,3) !< Unit reciplocal lattice vector [Bohr^-1]
Referenced by energy::atomic(), energy::ewald(), fftw_wrapper::fft_g2r_w(), fftw_wrapper::fft_r2g_w(), rho_v::generate_vps(), energy::hartree(), rho_v::init_rho_v(), stdin::read_stdin(), and energy::xc().
nelec
real(8), save atm_spec::nelec
Number of electrons per u.c.
Definition at line 50 of file atm_spec.F90.
Referenced by energy::ewald(), rho_v::init_rho_v(), k_point::ksum_rho(), and pp::read_pp().
avec
real(8), dimension(3,3), save atm_spec::avec
Unit lattice vector [Bohr].
Definition at line 50 of file atm_spec.F90.
Referenced by energy::ewald(), griddata::read_griddata(), stdin::read_stdin(), gvec::setup_gvec(), and griddata::write_griddata().
bvec
real(8), dimension(3,3), save atm_spec::bvec
Unit reciplocal lattice vector [Bohr^-1].
Definition at line 50 of file atm_spec.F90.
Referenced by diag_direct::direct(), energy::ewald(), plot::fermi_plot(), rho_v::generate_vps(), hamiltonian::h_psi(), energy::hartree(), rho_v::hartree_pot(), energy::kinetic(), k_point::ksum_dos(), k_point::ksum_rho(), lobpcg::lobpcg_main(), griddata::read_griddata(), stdin::read_stdin(), and gvec::setup_gvec().
atm
type(atm_t), dimension(:), allocatable, save atm_spec::atm
(nat) Atom
Definition at line 55 of file atm_spec.F90.
   type(atm_t),allocatable,save :: &
   & atm(:) !< (nat) Atom
Referenced by energy::ewald(), rho_v::generate_vps(), griddata::read_griddata(), pp::read_pp(), stdin::read_stdin(), and griddata::write_griddata().
spec
type(spec_t), dimension(:), allocatable, save atm_spec::spec
(ntyp) Species
Definition at line 57 of file atm_spec.F90.
   type(spec_t),allocatable,save :: &
   & spec(:) !< (ntyp) Species
Referenced by energy::ewald(), rho_v::generate_vps(), pp::read_pp(), and stdin::read_stdin().