pwdft: constant Module Reference
constant Module Reference
Variables
real(8), parameter pi = acos(-1.0d0)
real(8), parameter bohr2ang = 0.529177249d0
real(8), parameter htr2ev = 27.21138456d0
Variable Documentation
pi
real(8), parameter constant::pi = acos(-1.0d0)
Definition at line 25 of file constant.F90.
   real(8),parameter :: pi = acos(-1.0d0)
Referenced by energy::ewald(), rho_v::generate_vps(), energy::hartree(), rho_v::hartree_pot(), griddata::read_griddata(), stdin::read_stdin(), gvec::setup_gvec(), energy::xc(), and rho_v::xc_pot().
bohr2ang
real(8), parameter constant::bohr2ang = 0.529177249d0
Definition at line 26 of file constant.F90.
   real(8),parameter :: bohr2ang = 0.529177249d0
Referenced by stdin::read_stdin(), and griddata::write_griddata().
htr2ev
real(8), parameter constant::htr2ev = 27.21138456d0
Definition at line 27 of file constant.F90.
   real(8),parameter :: htr2ev = 27.21138456d0
Referenced by energy::atomic(), plot::band_plot(), energy::ewald(), plot::fermi_plot(), energy::hartree(), energy::kinetic(), k_point::ksum_dos(), pwdft(), stdin::read_stdin(), scf::scf_loop(), energy::total_e(), and energy::xc().