pwdft: /home/kawamura/program/pwdft/src/pwdft.F90 File Reference
pwdft.F90 File Reference
Functions/Subroutines
program pwdft
Function/Subroutine Documentation
pwdft()
program pwdft
Definition at line 30 of file pwdft.F90.
References plot::band_plot(), kohn_sham::calculation, kohn_sham::ef, kohn_sham::eval, kohn_sham::evec, plot::fermi_plot(), gvec::g_rh, gvec::g_wf, constant::htr2ev, fftw_wrapper::init_fft(), rho_v::init_rho_v(), scf::kohn_sham_eq(), k_point::ksum_dos(), kohn_sham::nbnd, k_point::nk, griddata::read_griddata(), pp::read_pp(), stdin::read_stdin(), scf::scf_loop(), energy::total_e(), rho_v::vks, and griddata::write_griddata().